# Configuração do Netlify para o frontend

[build]
  command = "npm run build"
  publish = "dist"

# Variáveis de ambiente (também configure no dashboard do Netlify)
[build.environment]
  NODE_VERSION = "18"

# Regras de redirecionamento para SPA (Vue Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança e CORS
[[headers]]
  for = "/*"
  [headers.values]
    # Permitir requisições para sua API
    Access-Control-Allow-Origin = "*"
    # Cache control
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
